### PR TITLE
Create DID trait and use Timestamp by trait

### PR DESCRIPTION
**Pull request by danforbes**
In use here https://github.com/substrate-developer-hub/substrate-enterprise-sample/compare/feat/did/trait

### CODE REVIEW

**Review by jimmychu0807 — APPROVED** [review]
nice update

**Review by riusricardo — APPROVED** [review]
Nice! Please merge until the other PR is ready.

**Comment by riusricardo** [comment]
Please update the HOWTO file to reflect this changes.

**Comment by danforbes** [comment]
@riusricardo I updated the HOWTO guide, but I'm not sure what you mean about the other PR.

**Comment by riusricardo** [comment]
For Enterprise Sample. But I'm now realizing that it is ok to merge because on the other repo we use the tag.

**Pull request merged**
